### ISSUE TITLE
We're both beaten.

### ISSUE THREAD

**Issue by FuzzyLitchi** [zvibazak/Nice-MD5s#4]
https://blog.youmu.moe/posts/finding-nice-md5s-using-rust/

I was beaten by roughly 2 months at doing it in rust lol.

**Comment by FuzzyLitchi** [comment]
For the record I got this one too.
```
π match with 10 characters! md5(56d2e3c0f08f1c8990a9f77138d640cb) 3141592653eed64be66b9a7ff45a4223
```

**Comment by zvibazak** [comment]
Hi very interesting article. Thanks!
I added a new section at the README.md files for links like you sent.

**Comment by zvibazak** [comment]
I added the π match with 10 characters!

**Comment by FuzzyLitchi** [comment]
oh the blog post isn't by me! That is someone else. Maybe you meant to say I submitted the article, but I think it reads as if I wrote it.

**Comment by zvibazak** [comment]
oh I fixed it, thanks
