### ISSUE TITLE
letters, nice match and e

### ISSUE THREAD

**Issue by johnmave126** [zvibazak/Nice-MD5s#6]
Didn't keep running the program after finishing the blog, so here are all I got:
`md5(s3i7gogs1gn9at6knh4sartreiqlppaa) = efadaefecffacfcdcebbafacbfeadbd3` which contains 31 leading letters
`md5(k4gdqjwk641meqx4fqinagckq4q6sqgk) = 777777777771313bfb8042d99437c4ff` which contains 11 leading consecutive 7's
`md5(6nencc64tsdhlmfa3ghsvnpe7i1us4ai) = 27182818284d93f1072d42d3b215d83b` which agrees with `e` for the first 11 characters.

**Comment by zvibazak** [comment]
Thanks - updated.
